apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: {{ .Values.global.namespace }}
  labels:
    app: loki
spec:
  replicas: {{ .Values.loki.replicas }}
  serviceName: loki
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      volumes:
        - name: config
          configMap:
            name: loki-config
      containers:
        - name: loki
          image: {{ .Values.loki.image }}
          args:
            - "-config.file=/etc/loki/loki-config.yaml"
          ports:
            - containerPort: 3100
            - containerPort: 9096
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: loki-data
              mountPath: /loki
          resources:
            {{- toYaml .Values.loki.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 15
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: loki-data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: {{ .Values.loki.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.loki.storage }}
