apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.slaAgentService.tenantRulesPvc }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.slaAgentService.tenantRulesStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.slaAgentService.tenantRulesStorage }}
