apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tenant-rules
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.prometheus.rulesStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.prometheus.rulesStorage }}
