apiVersion: v1
kind: Service
metadata:
  name: auth-server-svc
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: auth-server
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
