apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zeux-monitoring
  namespace: skala-argocd
spec:
  project: default
  source:
    repoURL: https://github.com/1team-zeux/zeux-gitops
    targetRevision: main
    path: zeux-monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: skala3-finalproj-class1-team1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
