apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlantis-data
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.atlantis.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.atlantis.storage }}
