apiVersion: v1
kind: Service
metadata:
  name: monitoring-api-svc
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: monitoring-api
  ports:
    - port: 8091
      targetPort: 8091
      protocol: TCP
  type: ClusterIP
