apiVersion: v1
kind: Service
metadata:
  name: 1team-mariadb-svc
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: 1team-mariadb
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
